(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#303030" :foreground "#dddddd" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Menlo"))))
 '(font-lock-builtin-face ((t (:foreground "#eeeeee" :weight normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8fcc8f"))))
 '(font-lock-comment-face ((t (:foreground "#8fcc8f"))))
 '(font-lock-constant-face ((t (:foreground "#bb88fcc"))))
 '(font-lock-function-name-face ((t (:foreground "#8fcca3"))))
 '(font-lock-keyword-face ((t (:foreground "#8fc2cc" :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#cc8fa3"))))
 '(font-lock-string-face ((t (:foreground "#cc8fa3"))))
 '(font-lock-type-face ((t (:foreground "#8fcca3" :slant normal))))
 '(font-lock-variable-name-face ((t (:foreground "#c28fcc"))))
 '(fringe ((t (:background "#333333" :foreground "#dddddd"))))
 '(linum ((t (:inherit default :background "#333333" :foreground "#dddddd" :underline nil))))
 '(markdown-header-delimiter-face ((t (:inherit markdown-markup-face :foreground "#cc8fa3"))))
 '(markdown-header-face ((t (:foreground "#cc8fa3"))))
 '(markdown-list-face ((t (:inherit markdown-markup-face :foreground "#c28fcc"))))
 '(markdown-markup-face ((t (:inherit \#cc8fa3 :slant normal :weight normal))))
 '(markdown-pre-face ((t (:inherit (markdown-code-face default)))))
 '(mode-line ((t (:foreground "#f9f9f9" :background "#bdbdbd" :box nil :height 140))))
 '(mode-line-active ((t (:foreground "#f9f9f9" :background "#AD1457" :box nil :height 140))))
 '(mode-line-inactive ((t (:foreground "#f9f9f9" :background "#666666" :box nil :height 140))))
 '(neo-dir-link-face ((t (:foreground "#8fb8cc"))))
 '(neo-header-face ((t (:background "#333333" :foreground "#dddddd"))))
 '(neo-root-dir-face ((t (:background "#333333" :foreground "#dddddd"))))
 '(neo-vc-default-face ((t (:foreground "#eeeeee"))))
 '(powerline-active0 ((t (:foreground "#f9f9f9" :background "#424242" :box nil :height 130))))
 '(powerline-active1 ((t (:foreground "#f9f9f9" :background "#E91E63" :box nil :height 130))))
 '(powerline-active2 ((t (:foreground "#f9f9f9" :background "#880E4F" :box nil :height 130))))
 '(region ((t (:inherit highlight :background "#AD1457"))))
 '(web-mode-builtin-face ((t (:foreground "#cc8fa3"))))
 '(web-mode-constant-face ((t (:foreground "#bb88fcc"))))
 '(web-mode-function-name-face ((t (:foreground "#8fcc8f"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#8fc2cc"))))
 '(web-mode-html-tag-face ((t (:foreground "#8fcca3"))))
 '(web-mode-json-context-face ((t (:foreground "#c28fcc"))))
 '(web-mode-json-key-face ((t (:foreground "#f2bb61"))))
 '(web-mode-keyword-face ((t (:foreground "#cc8fa3"))))
 '(web-mode-symbol-face ((t (:foreground "#c28fcc"))))
 '(web-mode-variable-name-face ((t (:foreground "#f2bb61")))))
